spring.application.name:
    springbootdeveloper

spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format-sql: true

        defer-datasource-initialization: true

    sql:
        init:
            mode: always

    datasource:
        url: jdbc:h2:mem:testdb
    
    h2:
        console:
            enabled: true